server:
  port: 8080
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tbd
    username: postgres
    password: pitufo
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: "org.hibernate.spatial.dialect.postgis.PostgisDialect"
    hibernate:
      ddl-auto: create
    database-platform: "org.hibernate.spatial.dialect.postgis.PostgisDialect"

